### PR TITLE
lr3

### PR DESCRIPTION
**Pull request by Klishchukk**
lr3

### CODE REVIEW

**Review by nekotov — APPROVED** [review]
LGTM!

**Comment by nekotov** [comment]
@MPTCourseTeacher, waiting for ur review

**Comment by Klishchukk** [comment]
@MPTCourseTeacher, waiting for ur review!

**Review by MPTCourseTeacher — APPROVED** [review]
Thank you for your PR. Let's wait for @nekotov approval and merge PR

**Comment by nekotov** [comment]
I`ve approved a week ago, to be precise 7 days and 4 hours ago.....

**Pull request merged**
